stages:
    - build
    - deploy
cache:
    key: ${CI_PROJECT_ID}
    paths:
        - .gradle/

variables:
    OWNER: telegram-sms
    REPO: telegram-rc


build:
    image: alvrme/alpine-android:android-36-jdk17
    stage: build
    before_script:
      - apk --update --no-cache add git openssl bash curl wget
      - apk add --no-cache binutils
      - extras ndk
      - wget https://github.com/tcnksm/ghr/releases/download/v0.17.0/ghr_v0.17.0_linux_amd64.tar.gz
      - tar -zxvf ghr_v0.17.0_linux_amd64.tar.gz

    only:
        - master
    script:
        - echo -n ${KEYSTORE} | base64 -d > app/keys.jks
        - git submodule update --init --recursive
        - export VERSION_CODE=${CI_PIPELINE_ID}
        - export VERSION_NAME=${CI_COMMIT_REF_NAME}-${CI_COMMIT_SHORT_SHA}
        - export GRADLE_USER_HOME=$(pwd)/.gradle && mkdir -p ${GRADLE_USER_HOME}
        - echo -e "org.gradle.jvmargs=-Xmx1536m\n org.gradle.parallel=true" >> ${GRADLE_USER_HOME}/gradle.properties
        - chmod +x ./gradlew
        - ./gradlew assembleRelease
        - git push --set-upstream https://${GITHUB_ACCESS_KEY}@github.com/${OWNER}/${REPO}.git HEAD:refs/heads/${CI_COMMIT_REF_NAME}
        - ghr_v0.17.0_linux_amd64/ghr -t "${GITHUB_ACCESS_KEY}" -u "${OWNER}" -r "${REPO}" -c ${CI_COMMIT_REF_NAME} --prerelease "$(date "+%Y%m%d%H%M")-${CI_COMMIT_REF_NAME}-${CI_COMMIT_SHORT_SHA}" "./app/build/outputs/apk/release/app-release.apk"
    artifacts:
        paths:
            - app/build/outputs/apk/release/app-release.apk
        expire_in: 1 week
